from typing import Dict, Any, List, Literal, Optional
from pydantic import BaseModel, Field, ConfigDict, field_validator, EmailStr
import logging

logger = logging.getLogger("SiteOfSites_AI")

class ChangeUsernameParams(BaseModel):
    model_config = ConfigDict(extra="ignore")
    new_username: str = Field(..., min_length=2, max_length=20)

class ChangeEmailParams(BaseModel):
    model_config = ConfigDict(extra="ignore")
    new_email: EmailStr = Field(..., max_length=255)

class HistoryItem(BaseModel):
    model_config = ConfigDict(extra="ignore")
    role: Literal["user", "assistant"]
    content: str = Field(..., min_length=1, max_length=1000)

class ChatRequest(BaseModel):
    model_config = ConfigDict(extra="ignore")
    message: str = Field(..., min_length=1, max_length=1500)
    history: List[HistoryItem] = Field(default_factory=list, max_length=10)
    is_authenticated: bool = False  # <--- Теперь бот знает о статусе пользователя

    @field_validator("message")
    @classmethod
    def not_blank(cls, v: str) -> str:
        v = v.strip()
        if not v:
            raise ValueError("Message cannot be empty or just whitespace")
        return v

class RawAction(BaseModel):
    """Схема, которую мы ожидаем от LLM при распознавании интента"""
    model_config = ConfigDict(extra="ignore") # Прощаем LLM лишние или забытые поля
    intent: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    reply_text: str = "" # Делаем поле необязательным

    def validate_params(self) -> Dict[str, Any]:
        """Дополнительная внутренняя валидация параметров в зависимости от интента"""
        valid_intents = ["general_query", "change_username", "change_email", "cancel_premium", "reset_password"]
        if self.intent not in valid_intents:
             raise ValueError(f"Unknown intent generated by LLM: {self.intent}")
             
        try:
            if self.intent == "change_username":
                return ChangeUsernameParams(**self.parameters).model_dump()
            if self.intent == "change_email":
                return ChangeEmailParams(**self.parameters).model_dump()
            return self.parameters
        except Exception as e:
            logger.warning(f"Parameter validation failed for intent {self.intent}: {e}")
            raise ValueError(f"Invalid parameters for {self.intent}")

class ChatResponse(BaseModel):
    reply: str
    intent: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None
    status: str = "success"
    source: Optional[str] = None